xposed: ui: Work around Jetpack Navigation issue
Tapping multiple navigation destinations at the same time results in a
crash due to a Jetpack Navigation issue [1] that Google is uninterested
in addressing:

java.lang.IllegalArgumentException: Navigation action/destination dev.kdrag0n.android12ext:id/action_settings_root_to_tweaks cannot be found from the current destination Destination(dev.kdrag0n.android12ext:id/system_settings) label=System class=dev.kdrag0n.android12ext.ui.settings.system.SystemSettingsFragment

[1] https://github.com/android/sunflower/issues/239